### PR TITLE
modifications to `child_filter.py`

### PR DESCRIPTION
**Pull request by jrsacher**
Changes:

+ Removed the need for `get_atom_props` function by adding
```python
values["num_carbons"] = len(mol.GetAtomsMatchingQuery(rdqueries.AtomNumEqualsQueryAtom(6)))
values["num_charges"] = sum((abs(atom.GetFormalCharge()) for atom in atoms))
values["max_ring_size"] = max((len(r) for r in mol.GetRingInfo().AtomRings()), default=0)
```
+ Added extra properties to `get_filter_values`. These do not yet have corresponding filter statements in `apply_filter` -- I didn't want to add anything that could cause a key error with older code.
```python
values["num_heavy_atoms"] = desc.CalcNumHeavyAtoms(mol)
values["fSP3"] = desc.CalcFractionCSP3(mol)
```
+ Removed duplication of effort in `if` statements in `apply_filter` by combining lower and upper bound checks with `or`

I've tested manually with a decent number of molecules, but a little extra testing wouldn't hurt.

### CODE REVIEW

**Comment by jrsacher** [comment]
Oh, now I see where the filter defaults are defined in the API. I'll add some suggested values and such in my next commit.

**Comment by aebrer** [comment]
since this changes the default filtering values, this is technically an API breaking update (since the default behaviour will change when filtering)

this means either the version (in `setup.py`) will need to be updated to a new major version
or
the changes to the filter will have to be introduced such that the new values are opt-in and off by default (setting an impossibly wide range is an acceptable if hacky way to do this)

**Comment by aebrer** [comment]
oh nvm
DUH 
I see you've already addressed this and they are in fact off by default!

**Comment by aebrer** [comment]
plz bump version to 2.9.0 and then I will merge and tag the new release :)

thanks @jrsacher great additions here!

**Pull request merged**
